'use strict';

// Parses ninja's build log into one shape the views can render.
//
// The file sits at the top of the build directory as `.ninja_log`, and ninja
// appends one tab-separated line per completed edge:
//
//   # ninja log v7
//   10  194  8104820215628786  libs/.../math_utils.cpp.obj  665c63a0cbc75772
//   ^    ^   ^                 ^                            ^
//   start end mtime            output                       command hash
//
// Times are milliseconds since that ninja invocation started, so `end - start`
// is how long the edge took and the columns say nothing about wall-clock dates.
//
// Verified against real output from ninja + MinGW on Windows; the fixtures in
// test/ninja are that output, regenerated by test/ninja/generate.sh.
//
// Only the Ninja generator writes this file. Visual Studio and Makefiles trees
// have no equivalent and nothing here invents one -- the same rule the map
// parser follows for lld.

const fs = require('fs');
const path = require('path');
const { artifactStem } = require('./mapFile');

// v5 introduced the five-column layout read here and v7 is what current ninja
// writes. Anything newer is parsed anyway rather than refused: the columns have
// not moved in years, and refusing to open a log because ninja moved to v8
// would be worse than reading it and saying the version is untested.
const FIRST_SUPPORTED_VERSION = 5;
const LAST_VERIFIED_VERSION = 7;

const BANNER = /^#\s*ninja log v(\d+)/;

function detectFormat(text) {
  const banner = BANNER.exec(text.slice(0, 200));
  return banner ? { format: 'ninja', version: Number(banner[1]) } : null;
}

// ---------------------------------------------------------------- shared

// What an output is, judged by its name alone. The distinction is what makes
// the numbers readable: compiling is many small edges and linking is a few
// large ones, and rolling them together hides both.
function outputKind(output) {
  const name = path.basename(String(output || ''));
  if (/\.(?:o|obj)$/i.test(name)) return 'compile';
  if (/\.(?:a|lib)$/i.test(name)) return 'archive';
  if (/\.(?:so|dll|dylib)(?:\.\d+)*$/i.test(name)) return 'link';
  if (/\.(?:exe|elf|out)$/i.test(name)) return 'link';
  // CMake's own re-runs, custom commands, and Unix executables with no
  // extension all land here. They are real build time and worth showing.
  return 'other';
}

// One edge can name several outputs, and ninja writes a line for each with
// identical timings -- a DLL and its import library are one link:
//
//   3167  3325  8104820248661472  libs/render_core/librender_core.dll     8d49...
//   3167  3325  8104820248661472  libs/render_core/librender_core.dll.a   8d49...
//
// Summing per output would count that link twice. Everything downstream works
// on edges instead, which is what actually ran.
function edgeKey(entry) {
  return entry.start + ':' + entry.end + ':' + entry.mtime + ':' + entry.hash;
}

function emptyModel(version, filePath) {
  return {
    format: 'ninja',
    version,
    // True when the banner is newer than anything checked against real output.
    unverifiedVersion: version > LAST_VERIFIED_VERSION,
    path: filePath,
    entries: [],
    builds: [],
    edges: [],
    malformed: 0
  };
}

// ---------------------------------------------------------------- parsing

function parse(text, filePath) {
  const detected = detectFormat(text);
  if (!detected) {
    throw new Error('Not a ninja build log: no "# ninja log" banner. ' +
                    'Only the Ninja generator writes one.');
  }
  if (detected.version < FIRST_SUPPORTED_VERSION) {
    throw new Error('This is ninja log v' + detected.version + ', which predates the ' +
                    'five-column layout. Run "ninja -t recompact" to rewrite it.');
  }

  const model = emptyModel(detected.version, filePath);
  const lines = text.split(/\r?\n/);

  // ninja appends on completion, so within one invocation the end column only
  // rises. A line that ends earlier than the one before it is the first line of
  // a later build, which is the only marker separating runs in the file.
  let previousEnd = -1;
  let build = -1;

  for (const line of lines) {
    if (!line || line.charAt(0) === '#') continue;

    const columns = line.split('\t');
    if (columns.length < 5) { model.malformed++; continue; }

    const start = Number(columns[0]);
    const end = Number(columns[1]);
    if (!Number.isFinite(start) || !Number.isFinite(end)) { model.malformed++; continue; }

    if (build < 0 || end < previousEnd) {
      build++;
      model.builds.push({ index: build, entries: [], start: start, end: end, wall: 0 });
    }
    previousEnd = end;

    const output = columns[3];
    const entry = {
      start,
      end,
      // A clock that only moves forward cannot produce a negative duration, but
      // a hand-edited or truncated log can. Clamp rather than let one bad row
      // subtract from every total above it.
      duration: Math.max(0, end - start),
      mtime: columns[2],
      output,
      hash: columns[4],
      kind: outputKind(output),
      build
    };

    model.entries.push(entry);
    const segment = model.builds[build];
    segment.entries.push(entry);
    if (start < segment.start) segment.start = start;
    if (end > segment.end) segment.end = end;
  }

  for (const segment of model.builds) {
    // What the build cost in real time, which is not the sum of its edges:
    // ninja runs several at once.
    segment.wall = Math.max(0, segment.end - segment.start);
  }

  return summarise(model);
}

/**
 * Reduces the raw lines to the freshest known timing for every output.
 *
 * An incremental build appends new lines without removing the old ones, so an
 * output that has been rebuilt appears more than once. The last line for it is
 * the current answer; earlier ones describe a compile that no longer happens
 * that way. Taking the last also means a full build followed by small
 * incremental ones still describes every target, which is what makes the
 * question "what is slow in this project" answerable at all.
 */
function summarise(model) {
  const latest = new Map();
  for (const entry of model.entries) latest.set(entry.output, entry);

  const byEdge = new Map();
  for (const entry of latest.values()) {
    const key = edgeKey(entry);
    let edge = byEdge.get(key);
    if (!edge) {
      edge = {
        key,
        start: entry.start,
        end: entry.end,
        duration: entry.duration,
        kind: entry.kind,
        build: entry.build,
        outputs: []
      };
      byEdge.set(key, edge);
    }
    edge.outputs.push(entry.output);
    // A DLL and its import library share an edge; call it a link rather than
    // letting whichever output was seen first decide.
    if (entry.kind !== 'other' && edge.kind === 'other') edge.kind = entry.kind;
  }

  for (const edge of byEdge.values()) edge.outputs.sort();

  const edges = Array.from(byEdge.values()).sort((a, b) => b.duration - a.duration);
  const byKind = new Map();
  let cpu = 0;
  for (const edge of edges) {
    cpu += edge.duration;
    byKind.set(edge.kind, (byKind.get(edge.kind) || 0) + edge.duration);
  }

  model.latest = latest;
  model.edges = edges;
  model.lastBuild = model.builds.length ? model.builds[model.builds.length - 1] : null;
  model.totals = {
    // Time spent compiling and linking, added up. With N jobs in flight the
    // build finishes well inside this, so it is the work rather than the wait.
    cpu,
    edges: edges.length,
    byKind,
    // The wait, for the most recent run in the file.
    wall: model.lastBuild ? model.lastBuild.wall : 0
  };
  return model;
}

// A build log is one line per edge, so even a very large project keeps this in
// the low megabytes. A file past this is not a build log.
const MAX_LOG_BYTES = 128 * 1024 * 1024;

function parseFile(filePath) {
  let size = 0;
  try {
    size = fs.statSync(filePath).size;
  } catch (e) {
    // Let readFileSync produce the real error.
  }
  if (size > MAX_LOG_BYTES) {
    throw new Error(path.basename(filePath) + ' is ' + Math.round(size / (1024 * 1024)) +
                    ' MB, which is far larger than any build log; refusing to read it.');
  }
  return parse(fs.readFileSync(filePath, 'utf8'), filePath);
}

// ninja keeps the log at the root of the build directory, so this stays very
// shallow: it is looking for sibling build trees, not scanning a project.
function findBuildLogs(root, maxDepth) {
  if (maxDepth === undefined) maxDepth = 3;
  const skip = new Set(['CMakeFiles', '.cmake', '_deps', 'node_modules', '.git']);
  const found = [];

  const walk = (dir, depth) => {
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch (e) {
      return;
    }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isFile() && entry.name === '.ninja_log') {
        found.push(full);
      } else if (entry.isDirectory() && depth < maxDepth &&
                 !entry.name.startsWith('.') && !skip.has(entry.name)) {
        walk(full, depth + 1);
      }
    }
  };

  walk(root, 0);
  return found.sort();
}

// ---------------------------------------------------------- join with targets

/**
 * Works out how much of the build time each CMake target accounts for.
 *
 * The same join the linker map does, from the other side: the log knows
 * `libs/engine/CMakeFiles/engine.dir/engine.cpp.obj` took 203 ms, and CMake
 * knows that path belongs to target "engine". Three routes, most specific first:
 *
 *   1. CMake's layout, which puts a target's objects under <target>.dir/
 *   2. an output named exactly like the target's nameOnDisk
 *   3. the same stem, for when the log and the build tree came off different
 *      machines (libengine.a here, engine.lib there)
 *
 * @returns {Map<string, {compile: number, link: number, total: number,
 *                        edges: object[], slowest: object|null}>}
 *          keyed by target id; targets nothing was built for are simply missing.
 */
function matchTargets(targetModel, logModel) {
  const byArtifact = new Map();
  const byObjectDir = new Map();
  // Windows and the default macOS volume do not distinguish case, and CMake and
  // ninja need not agree on it. Comparing raw would drop the whole join.
  const fold = (text) => String(text || '').toLowerCase();

  for (const target of targetModel.targets.values()) {
    if (target.nameOnDisk) byArtifact.set(fold(target.nameOnDisk), target);
    byObjectDir.set(fold(target.name) + '.dir', target);
  }

  // Two targets can reduce to the same stem (foo.lib beside libfoo.a). Crediting
  // one of them would be a guess, so drop the stem and leave those to the exact
  // routes -- the rule the map join already follows.
  const byStem = new Map();
  const ambiguous = new Set();
  for (const target of targetModel.targets.values()) {
    if (!target.nameOnDisk) continue;
    const stem = artifactStem(target.nameOnDisk);
    if (!stem) continue;
    if (byStem.has(stem)) ambiguous.add(stem);
    else byStem.set(stem, target);
  }
  for (const stem of ambiguous) byStem.delete(stem);

  const matched = new Map();

  for (const edge of logModel.edges) {
    let target = null;

    for (const output of edge.outputs) {
      if (target) break;
      // Both separators appear: ninja writes forward slashes, but a path that
      // came through CMake on Windows can carry backslashes -- the same thing
      // that once stopped executables matching in the map join.
      const dir = /(?:^|[\\/])([^\\/]+)\.dir(?:[\\/]|$)/.exec(output);
      if (dir) target = byObjectDir.get(fold(dir[1]) + '.dir');
    }
    for (const output of edge.outputs) {
      if (target) break;
      target = byArtifact.get(fold(path.basename(output)));
    }
    // Only once every exact route has missed, and never for object files:
    // those keep their own names across platforms, so stemming app.cpp.obj
    // would credit it to a target called app rather than to the directory it
    // was compiled in.
    if (!target && edge.kind !== 'compile') {
      for (const output of edge.outputs) {
        if (target) break;
        target = byStem.get(artifactStem(path.basename(output)));
      }
    }
    if (!target) continue;

    let row = matched.get(target.id);
    if (!row) {
      row = { compile: 0, link: 0, total: 0, edges: [], slowest: null };
      matched.set(target.id, row);
    }
    if (edge.kind === 'compile') row.compile += edge.duration;
    else row.link += edge.duration;
    row.total += edge.duration;
    row.edges.push(edge);
    if (!row.slowest || edge.duration > row.slowest.duration) row.slowest = edge;
  }

  for (const row of matched.values()) {
    row.edges.sort((a, b) => b.duration - a.duration);
  }
  return matched;
}

// ---------------------------------------------------------------- diff

/**
 * Compares two logs edge by edge, keyed by output.
 *
 * @returns {{
 *   total: {before: number, after: number, delta: number},
 *   outputs: Array<{key, kind, before, after, delta, status}>
 * }}
 */
function diff(before, after) {
  const durations = (model) => {
    const map = new Map();
    // Keyed on the first output so a multi-output edge is one row, matching how
    // it is counted in the totals.
    for (const edge of model.edges) map.set(edge.outputs[0], edge);
    return map;
  };

  const beforeEdges = durations(before);
  const afterEdges = durations(after);
  const keys = new Set([...beforeEdges.keys(), ...afterEdges.keys()]);
  const outputs = [];

  for (const key of keys) {
    const b = beforeEdges.get(key);
    const a = afterEdges.get(key);
    const beforeMs = b ? b.duration : 0;
    const afterMs = a ? a.duration : 0;
    if (beforeMs === afterMs) continue;
    outputs.push({
      key,
      kind: (a || b).kind,
      before: beforeMs,
      after: afterMs,
      delta: afterMs - beforeMs,
      status: !b ? 'added' : !a ? 'removed' : 'changed'
    });
  }

  outputs.sort((x, y) => Math.abs(y.delta) - Math.abs(x.delta));

  return {
    total: {
      before: before.totals.cpu,
      after: after.totals.cpu,
      delta: after.totals.cpu - before.totals.cpu
    },
    outputs
  };
}

// Milliseconds are what the log carries and what short edges need, but a link
// measured in thousands of them is unreadable. Same ladder as formatBytes.
function formatMs(value) {
  const sign = value < 0 ? '-' : '';
  const ms = Math.abs(Math.round(value));
  if (ms < 1000) return sign + ms + ' ms';
  if (ms < 60000) return sign + (ms / 1000).toFixed(1) + ' s';
  const minutes = Math.floor(ms / 60000);
  const seconds = Math.round((ms % 60000) / 1000);
  // 1 m 60 s would be a rounding artefact, not a time.
  if (seconds === 60) return sign + (minutes + 1) + ' m 00 s';
  return sign + minutes + ' m ' + String(seconds).padStart(2, '0') + ' s';
}

module.exports = {
  detectFormat,
  parse,
  parseFile,
  findBuildLogs,
  summarise,
  matchTargets,
  diff,
  outputKind,
  formatMs
};
